### ISSUE TITLE
Crash when looking inside the matter decomposer

### ISSUE THREAD

**Issue by AshbyCoco** [simeonradivoev/MatterOverdrive#204]
Shift clicked inside the matter decomposer with the matter scanner. On version 1.7.10-0.4.0-RC3

```
---- Minecraft Crash Report ----
// My bad.

Time: 8/31/15 5:21 PM
Description: Rendering screen

java.lang.ArithmeticException: / by zero
	at matteroverdrive.tile.TileEntityMachineDecomposer.getEnergyDrainPerTick(TileEntityMachineDecomposer.java:192)
	at matteroverdrive.gui.GuiDecomposer.ManageReqiremnetsTooltips(GuiDecomposer.java:86)
	at matteroverdrive.gui.GuiDecomposer.func_146976_a(GuiDecomposer.java:76)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at cofh.lib.gui.GuiBase.func_73863_a(GuiBase.java:86)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at matteroverdrive.tile.TileEntityMachineDecomposer.getEnergyDrainPerTick(TileEntityMachineDecomposer.java:192)
	at matteroverdrive.gui.GuiDecomposer.ManageReqiremnetsTooltips(GuiDecomposer.java:86)
	at matteroverdrive.gui.GuiDecomposer.func_146976_a(GuiDecomposer.java:76)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at cofh.lib.gui.GuiBase.func_73863_a(GuiBase.java:86)

-- Screen render details --
Details:
	Screen name: matteroverdrive.gui.GuiDecomposer
	Mouse location: Scaled: (213, 119). Absolute: (427, 240)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [EntityClientPlayerMP['DoubleCompressed'/267145, l='MpServer', x=27.95, y=69.59, z=-52.79], EntityOtherPlayerMP['zephoss'/266893, l='MpServer', x=7.53, y=70.00, z=75.38], EntityOtherPlayerMP['SoulFist'/266244, l='MpServer', x=1.57, y=68.04, z=76.99]]
	Chunk stats: MultiplayerChunkCache: 399, 399
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (9,70,0), Chunk: (at 9,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2209687 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 19 total; [EntityOtherPlayerMP['SoulFist'/266244, l='MpServer', x=1.57, y=68.04, z=76.99], EntityOtherPlayerMP['SoulFist'/266244, l='MpServer', x=1.57, y=68.04, z=76.99], EntityClientPlayerMP['DoubleCompressed'/267145, l='MpServer', x=27.95, y=69.59, z=-52.79], EntityHat['unknown'/359, l='MpServer', x=27.95, y=69.59, z=-52.79], EntityHat['unknown'/360, l='MpServer', x=7.53, y=70.00, z=75.38], EntitySmallEarthGolem['Small Earth Golem'/265, l='MpServer', x=-45.47, y=68.00, z=-30.88], EntityOtherPlayerMP['zephoss'/266893, l='MpServer', x=7.53, y=70.00, z=75.38], EntityHat['unknown'/361, l='MpServer', x=1.57, y=68.04, z=76.99], EntityItem['item.item.matter_scanner'/271918, l='MpServer', x=31.11, y=68.33, z=-54.77], EntityTrail['unknown'/363, l='MpServer', x=27.95, y=69.59, z=-52.79], EntityTrail['unknown'/364, l='MpServer', x=7.53, y=70.00, z=75.38], EntityTrail['unknown'/365, l='MpServer', x=1.57, y=68.04, z=76.99], EntitySpark['Spark'/9006, l='MpServer', x=17.50, y=69.50, z=-63.50], EntityItemFrame['Item Frame'/9007, l='MpServer', x=-17.94, y=69.50, z=-52.50], EntityItemFrame['Item Frame'/9008, l='MpServer', x=-17.94, y=69.50, z=-53.50], EntityItemFrame['Item Frame'/9009, l='MpServer', x=-17.94, y=69.50, z=-54.50], EntitySpark['Spark'/9010, l='MpServer', x=16.50, y=69.50, z=-65.50], EntityVillagerMadScientist['Mad Scientist'/9011, l='MpServer', x=-36.63, y=66.00, z=-59.16], EntityOtherPlayerMP['zephoss'/266893, l='MpServer', x=7.53, y=70.00, z=75.38]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1222887072 bytes (1166 MB) / 2112618496 bytes (2014 MB) up to 3186360320 bytes (3038 MB)
	JVM Flags: 10 total; -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=50 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseCodeCacheFlushing -XX:ParallelGCThreads=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx3072m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1470 Optifine OptiFine_1.7.10_HD_U_C1 117 mods loaded, 117 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1470-1.7.10-universal.jar) 
	UCHIJA	Forge{10.13.4.1470} [Minecraft Forge] (forge-1.7.10-10.13.4.1470-1.7.10-universal.jar) 
	UCHIJA	appliedenergistics2-core{rv2-stable-9} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJA	betterfps{1.0.0} [BetterFps] (minecraft.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHIJA	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHIJA	appliedenergistics2{rv2-stable-9} [Applied Energistics 2] (appliedenergistics2-rv2-stable-9.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	aura{unspecified} [Aura Cascade] (AuraCascade-551.jar) 
	UCHIJA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJA	AWWayofTime{v1.3.2} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.2-1.jar) 
	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJA	Botania{r1.7-215} [Botania] (Botania r1.7-215.jar) 
	UCHIJA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJA	BuildCraft|Core{7.0.21} [BuildCraft] (buildcraft-7.0.21.jar) 
	UCHIJA	BuildCraft|Silicon{7.0.21} [BC Silicon] (buildcraft-7.0.21.jar) 
	UCHIJA	BuildCraft|Factory{7.0.21} [BC Factory] (buildcraft-7.0.21.jar) 
	UCHIJA	BuildCraft|Builders{7.0.21} [BC Builders] (buildcraft-7.0.21.jar) 
	UCHIJA	BuildCraft|Energy{7.0.21} [BC Energy] (buildcraft-7.0.21.jar) 
	UCHIJA	BuildCraft|Robotics{7.0.21} [BC Robotics] (buildcraft-7.0.21.jar) 
	UCHIJA	BuildCraft|Transport{7.0.21} [BC Transport] (buildcraft-7.0.21.jar) 
	UCHIJA	BuildCraft|Compat{7.0.8} [BuildCraft Compat] (buildcraft-compat-7.0.8.jar) 
	UCHIJA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
	UCHIJA	IC2{2.2.767-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.767-experimental.jar) 
	UCHIJA	Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar) 
	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) 
	UCHIJA	D3Core{1.1.0.31} [D3Core] (D3Core-1.7.10-1.1.0.31.jar) 
	UCHIJA	darkcore{0.3} [Dark Core] (darkcore-0.3-45.jar) 
	UCHIJA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJA	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) 
	UCHIJA	EnderZoo{1.7.10-1.0.15.32} [Ender Zoo] (EnderZoo-1.7.10-1.0.15.32.jar) 
	UCHIJA	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	extracells{2.2.68} [ExtraCells] (ExtraCells-1.7.10-2.2.69bNIGHTLY.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJA	ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
	UCHIJA	ImmersiveEngineering{0.5.4} [Immersive Engineering] (ImmersiveEngineering-0.5.4.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCHIJA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJA	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) 
	UCHIJA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJA	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCHIJA	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
	UCHIJA	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJA	mo{0.4.0-RC3} [Matter Overdrive] (MatterOverdrive-1.7.10-0.4.0-RC3.jar) 
	UCHIJA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) 
	UCHIJA	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
	UCHIJA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJA	NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	neiintegration{1.0.12} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.12.jar) 
	UCHIJA	neresources{0.1.0.101} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.101.jar) 
	UCHIJA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJA	MapWriter{2.1.2} [MapWriter] (Opis-1.2.5_1.7.10.jar) 
	UCHIJA	Opis{1.2.5} [Opis] (Opis-1.2.5_1.7.10.jar) 
	UCHIJA	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.114-universal.jar) 
	UCHIJA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJA	ttCore{MC1.7.10-0.1.1-76} [ttCore] (ttCore-MC1.7.10-0.1.1-76.jar) 
	UCHIJA	RArm{1.7.10-1.2.0-32} [Redstone Armory] (RedstoneArmory-1.7.10-1.2.0-32.jar) 
	UCHIJA	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
	UCHIJA	TardisMod{0.99} [Tardis Mod] (tardismod-1.7.10-0.99-207.jar) 
	UCHIJA	tcnodetracker{1.1.2} [TC Node Tracker] (tcnodetracker-1.7.10-1.1.2.jar) 
	UCHIJA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJA	TU{1.0} [Thaumic Upholstry] (Thaumic_Upholstery-1.2_1.7.10.jar) 
	UCHIJA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-37.jar) 
	UCHIJA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJA	TravellersGear{1.16.3} [Traveller's Gear] (TravellersGear-1.7.10-1.16.3.jar) 
	UCHIJA	VersionChecker{1.1.9} [Version Checker] (VersionChecker-1.1.9.jar) 
	UCHIJA	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHIJA	wailaplugins{MC1.7.10-0.0.1-14} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-14.jar) 
	UCHIJA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar) 
	UCHIJA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJA	YABM{1.0.6} [Yet Another Backup Mod] (YABM-1.7.10-1.0.6.jar) 
	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UCHIJA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	UCHIJA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.0' Renderer: 'AMD Radeon HD 5450'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-9 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalFoundation: -[1.7.10]1.2.0-102
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.1-89
	ThermalDynamics: -[1.7.10]1.1.0-161
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 5450 GL version 4.5.13399 Compatibility Profile Context 15.200.1062.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

Edit (shadowfacts): Formatting

**Comment by simeonradivoev** [comment]
how much matter did the scanner have ?

**Comment by simeonradivoev** [comment]
Also what upgrades did the matter decomposer have and did you try the latest hotfix ?

**Comment by AshbyCoco** [comment]
I dont know, i would say roughly around 900 and i did not. Breaking it seemed to fix it.

**Comment by simeonradivoev** [comment]
There was a bug that was fixed in the hotfix. If you had more than 2 Hyper Speed upgrades the speed will go to 0. You crash says the same thing. That's why I'm asking if the machine had any upgrades. Try out the hotfix and see if it happens again.

**Comment by AshbyCoco** [comment]
okay, ill try that, thanks. The machine had no upgrades

**Comment by NullMagic** [comment]
Using hotfix 3 we still get this crash when 3 hyper speed upgrades are placed in a matter decomposer.

http://pastebin.com/Fwz4adJS

**Comment by simeonradivoev** [comment]
what is the % of the speed

**Comment by NullMagic** [comment]
The percentage went to 0, I think, but I didn't see much before the crash forced me out

**Comment by simeonradivoev** [comment]
similar to #190 fixed in  2fb0982ea2f00a357b62eb27800158227f3749ad
