### ISSUE TITLE
Server Side Crash

### ISSUE THREAD

**Issue by Reginald-Halifrax** [simeonradivoev/MatterOverdrive#380]
So i ran into a issue with the new update but it seems to only happen if the server runs it. [Error.txt](https://github.com/simeonradivoev/MatterOverdrive/files/83155/Error.txt)

I can't figure out the error. any help would be great

**Comment by simeonradivoev** [comment]
Fixed in 58e80dd0d8f0b0f780acce731bc5a4446f16d5f7

**Comment by Reginald-Halifrax** [comment]
Not to necro this immediately but it seems even with it disabled the issue remains 
[Matter Overdrive Config.txt](https://github.com/simeonradivoev/MatterOverdrive/files/83169/Matter.Overdrive.Config.txt)
[Error.txt](https://github.com/simeonradivoev/MatterOverdrive/files/83170/Error.txt)

I don't want to have to sit here with the issue any more than you do.

**Comment by simeonradivoev** [comment]
You will have to download the latest dev builds or just wait for the hotfix.

**Comment by Reginald-Halifrax** [comment]
Alright then
