### ISSUE TITLE
Crash when scanning Redstone Ore

### ISSUE THREAD

**Issue by viper2g1** [simeonradivoev/MatterOverdrive#444]
The crash happens when I try to scan a piece of redstone ore with the matter scanner.

Here is the crash:

http://pastebin.com/ttbMuHwD

**Comment by shadowfacts** [comment]
Already fixed in cdb57fd74822c5e0d58b9950ef537e32e672ccdb. Update to the latest dev build, to get the fix. If you can't update, scan the Redstone dust instead of the ore.

**Comment by viper2g1** [comment]
I updated to the newest dev build (MatterOverdrive-1.7.10-0.4.1-build-18.jar) and still get the crash.  

Here is the log genereated:

http://pastebin.com/bzTaVqaZ
