### ISSUE TITLE
Error involving Mad Scientist

### ISSUE THREAD

**Issue by Hunterreaper** [simeonradivoev/MatterOverdrive#663]
When I walked up to him my game crashed. Loaded the game back up and talked to him then my game crashed again and now I can't load the world without the game immediately crashing
error: http://pastebin.com/r7dipKp4

**Comment by shadowfacts** [comment]
Already fixed in 623aad4c5ed73264bb0d97b47b785228dda84dd5.

**Comment by Hunterreaper** [comment]
Still getting the error despite that. Must be either my computer is being a piece of s**t again or another mod that's causing the problem

**Comment by shadowfacts** [comment]
The version with the fix hasn't been released yet.

**Comment by Hunterreaper** [comment]
ah
